Itech_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
#from registration.backends.simple.views import RegistrationView

#class MyRegistrationView(RegistrationView):
#    def get_success_url(self,request, user):
#        return '/rmb/'

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Itech_project.views.home', name='home'),
    url(r'^rmb/', include('RMB.urls')),
    url(r'^admin/', include(admin.site.urls)),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout',
     {'next_page': '/rmb/'}), #redirect on logout to main page, avoiding the logout window
    url(r'^accounts/', include('allauth.urls')),
    #url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    #(r'^accounts/', include('registration.backends.simple.urls')),
)
if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

RMB/urls.py
from django.conf.urls import patterns, url
from RMB import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^like_image/$', views.like_image, name='like_image'),
    url(r'^dislike_image/$', views.dislike_image, name='dislike_image'),
	url(r'^comment_image/$', views.comment_image, name='comment_image'),
	url(r'^worst_image/$', views.worst_image, name='worst_image'),
	url(r'^profile/$', views.upload_images, name='upload_images'),
    url(r'^newest/$', views.newest, name='newest'),
    url(r'^worse/$', views.worse, name='worse'),
    url(r'^noob/$', views.noob, name='noob'),
    url(r'^full/$', views.full, name='full'),
    url(r'^half/$', views.half, name='half'),
    url(r'^moustache/$', views.moustache, name='moustache'),
    )+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	

RMB/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from allauth.account.models import EmailAddress
import datetime
from allauth.socialaccount.models import SocialAccount
import hashlib

try:
    from django.utils.timezone import now
except ImportError:
    now = datetime.now
	
# UserProfile table extending User model
class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='profile')
    name = models.CharField(max_length=40, blank=True)
    surname = models.CharField(max_length=70, blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    last_login = models.DateTimeField(auto_now_add=True)
    # This line is required. Links UserProfile to a User model instance.
    def __unicode__(self):
        return self.user.username

    class Meta:
        db_table = 'user_profile'
    #if account if verified return email addresses
    def account_verified(self):
        if self.user.is_authenticated:
            result = EmailAddress.objects.filter(email=self.user.email)
            if len(result):
                return result[0].verified
        return False
 
	User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])
    # Override the __unicode__() method to return out something meaningful!
#
def profile_image_url(self):
    fb_uid = SocialAccount.objects.filter(user_id=self.user.id, provider='facebook')
 
    if len(fb_uid):
        return "http://graph.facebook.com/{}/picture?width=40&height=40".format(fb_uid[0].uid)
        return "http://www.gravatar.com/avatar/{}?s=40".format(hashlib.md5(self.user.email).hexdigest())
		
# Categories model included category names
class Categories(models.Model):
    cat_descr = models.CharField(max_length =120, blank=False)

    def __unicode__(self):
       return self.cat_descr

#images model
class Images(models.Model):
    image = models.ImageField(upload_to='images', blank=False)
    img_name = models.CharField(max_length=120, blank=True)
    img_date = models.DateTimeField(auto_now_add=True)
    img_user = models.ForeignKey(User)
    img_cat_id = models.ForeignKey(Categories)
    
    def __unicode__(self):
        return self.img_name

#comments model
class Comments(models.Model):
    com_descr = models.CharField(max_length=400, blank=True, default='')
    com_by = models.ForeignKey(User)
    img_commented = models.ForeignKey(Images, default='')
    com_date_added = models.DateTimeField(auto_now_add=True)
    com_date_changed = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
       return self.com_descr

#likes model
class Likes(models.Model):
    image_liked = models.ForeignKey(Images, null=True)
    likes = models.IntegerField(blank=False , default=0)
    dislikes = models.IntegerField(blank=False, default=0)
	
    def __unicode__(self):
        return str(self.image_liked)

RMB/forms.py
from django import forms
from django.contrib.auth.models import User
from RMB.models import UserProfile, Images
#form for uploading images
class UploadImagesForm(forms.ModelForm):

    class Meta:
        model = Images
        fields=('image','img_name','img_cat_id')

RMB/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login , logout
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response
from django.template import RequestContext
from RMB.models import Likes,Comments, Images,Categories
from django.contrib.auth.decorators import login_required
from RMB.forms import UploadImagesForm

# Index page view
def index(request):
    context = RequestContext(request)
    context_dict = {}
    try:
        # RECENT LIKES with comments limit 9 per page
        image_likes = Likes.objects.order_by('-likes')[:9]
        all_comments = Comments.objects.order_by('-com_date_added') 
        context_dict['image_likes'] = image_likes
        context_dict['all_comments'] = all_comments
    except Likes.DoesNotExist:
        pass
    except Comments.DoesNotExist:
        pass
    return render_to_response('rmb/index.html', context_dict, context)



def worst_image(request):
    context = RequestContext(request)
    context_dict={}
    image_id = None
    if request.method=='GET':
        image_id=request.GET['worst_id']
    if image_id:
        image_likes = Images.objects.order_by('-dislikes') [:9]
        context_dict['image_likes'] = image_likes
    return render_to_response('rmb/worst_image.html', context_dict,context)

#commenting an image view
@login_required
def comment_image(request):
    cat_id = None
    com_id = None
    cat_id = request.GET['comment_id']
    com_id = request.GET['com']
 
    if cat_id:
        cat = Likes.objects.get(id=int(cat_id))
        print(cat.image_liked.img_user)
        new_entry = Comments(com_descr=com_id, com_by=request.user, img_commented=cat.image_liked)
        new_entry.save()
    return HttpResponse(comments)

#like an image view /w get ajax request, user needs to be registered
@login_required
def like_image(request):
    cat_id = None
    if request.method == 'GET':
        
        cat_id = request.GET['like_id']

    likes = 0
    if cat_id:
        cat = Likes.objects.get(id=int(cat_id))
        if cat:
            likes = cat.likes + 1
            cat.likes =  likes
            cat.save()

    return HttpResponse(likes)

#dislike an image view /w get ajax request, user needs to be registered
@login_required
def dislike_image(request):
    cat_id = None
    if request.method == 'GET':
        
        cat_id = request.GET['dislike_id']

    dislikes = 0
    if cat_id:
        cat = Likes.objects.get(id=int(cat_id))
        if cat:
            dislikes = cat.dislikes + 1
            cat.dislikes =  dislikes
            cat.save()

    return HttpResponse(dislikes)
	
#Must be signed in.
#Page to Upload images
#User can also view previous uploads.
@login_required
def upload_images(request):
    context = RequestContext(request)
    context_dict={}

    if request.method == 'POST': 
	#processes form
        form = UploadImagesForm(request.POST, request.FILES)

        if form.is_valid():

            upload_image = form.save(commit=False)
            upload_image.img_user = request.user
	

            if 'image' in request.FILES:
                upload_image.image  =request.FILES['image']
            print upload_image.img_user
            upload_image.save()
            #next sequence of code will send the image back as form is sent
            form = UploadImagesForm()
            context_dict = {'upload_image': form}
            all_images = Images.objects.filter(img_user=request.user)
            context_dict['all_images']=all_images
            #Likes created to associate likes to image
            like = Likes(likes=0,dislikes=0)
            like.image_liked=upload_image
            print like
            print 'helo'
            like.save()
            context_dict['like']=like


            return render(request, 'rmb/profile.html', context_dict)

        else:
            print form.errors

    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
    else:
        form = UploadImagesForm()
        context_dict = {'upload_image': form}
        all_images = Images.objects.filter(img_user=request.user)
        context_dict['all_images']=all_images
        all_cats = Categories.objects.all()
        context_dict['all_cats']=all_cats


        return render_to_response('rmb/profile.html', context_dict, context)

#newest images page
def newest(request):
    context = RequestContext(request)
    context_dict={}

    try:
        
        all_images = Images.objects.order_by('-img_date')
        image_likes = Likes.objects.all()
        context_dict['all_images']=all_images
        all_comments = Comments.objects.all()
        context_dict['image_likes'] = image_likes
        context_dict['all_comments'] = all_comments


    except Images.DoesNotExist:
        pass
    except Likes.DoesNotExist:
        pass
    except Comments.DoesNotExist:
        pass
    return render_to_response('rmb/newest.html', context_dict, context)

# noob beard images page
def noob(request):
    context = RequestContext(request)
    context_dict={}

    try:
        # RECENT RATINGS
        all_images = Images.objects.filter(img_cat_id='4')
        context_dict['all_images']=all_images
        image_likes = Likes.objects.all()
        all_comments = Comments.objects.all()
        context_dict['image_likes'] = image_likes
        context_dict['all_comments'] = all_comments


    except Images.DoesNotExist:
        pass
    except Likes.DoesNotExist:
        pass
    except Comments.DoesNotExist:
        pass
    return render_to_response('rmb/noob.html', context_dict, context)

#moustache images page
def moustache(request):
    context = RequestContext(request)
    context_dict={}

    try:
        # RECENT RATINGS
        all_images = Images.objects.filter(img_cat_id='3')
        context_dict['all_images']=all_images
        image_likes = Likes.objects.all()
        all_comments = Comments.objects.all()
        context_dict['image_likes'] = image_likes
        context_dict['all_comments'] = all_comments


    except Images.DoesNotExist:
        pass
    except Likes.DoesNotExist:
        pass
    except Comments.DoesNotExist:
        pass
    return render_to_response('rmb/moustache.html', context_dict, context)

#half beard images page
def half(request):
    context = RequestContext(request)
    context_dict={}

    try:
        # RECENT RATINGS
        all_images = Images.objects.filter(img_cat_id='2')
        context_dict['all_images']=all_images
        image_likes = Likes.objects.all()
        all_comments = Comments.objects.all()
        context_dict['image_likes'] = image_likes
        context_dict['all_comments'] = all_comments


    except Images.DoesNotExist:
        pass
    except Likes.DoesNotExist:
        pass
    except Comments.DoesNotExist:
        pass
    return render_to_response('rmb/half.html', context_dict, context)

#full beard images beard
def full(request):
    context = RequestContext(request)
    context_dict={}

    try:
        # RECENT RATINGS
        all_images = Images.objects.filter(img_cat_id='1')
        context_dict['all_images']=all_images
        image_likes = Likes.objects.all()
        all_comments = Comments.objects.all()
        context_dict['image_likes'] = image_likes
        context_dict['all_comments'] = all_comments

    except Images.DoesNotExist:
        pass
    except Likes.DoesNotExist:
        pass
    except Comments.DoesNotExist:
        pass
    return render_to_response('rmb/full.html', context_dict, context)

def worse(request):
    context = RequestContext(request)
    context_dict = {}
    try:
        # RECENT RATINGS
        image_likes = Likes.objects.order_by('-dislikes')[:9]
        all_comments = Comments.objects.order_by('com_date_added')
        context_dict['image_likes'] = image_likes
        context_dict['all_comments'] = all_comments
    except Images.DoesNotExist:
        pass
    except Likes.DoesNotExist:
        pass
    except Comments.DoesNotExist:
        pass
    return render_to_response('rmb/worse.html', context_dict, context)

templates/rmb/base.html
<!DOCTYPE html>
{% load account %}
{% load staticfiles %}

<html>
    <head>
	<style type="text/css"> </style>
		<meta charset ="UTF-8">
        <!-- load bootstrap's and our own stylesheets -->
		<link rel="stylesheet" href="//netdna.bootstrapcdn.com/twitter-bootstrap/3.3.2/css/bootstrap-combined.min.css" />
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" />
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css" />
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/4.2.1/bootstrap-social.css" />
        <link rel="stylesheet" type="text/css" href="{% static "css/stylesheet.css" %}" /> <!-- our css -->
        <!-- empty base title -->
        <title>RMB - {% block title %}{% endblock %}</title>
    </head>

    <body>
    <!-- a bootstrap navigation bar -->
     <nav class="navbar navbar-default navbar-static-top">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<a class="navbar-brand" href="">RMB</a>
			</div>
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">			
			<ul class="nav navbar-nav navbar-right">
                <!-- if user is logged in -->
				{% if user.is_authenticated %}
                            <!-- and if user is logged in with a social application then create dropdown for social applications -->
							 {% if request.user.first_name or request.user.last_name %}
								<li class="divider-vertical"></li> 
								<img src="{{ request.user.profile.profile_image_url }}"/> <!-- not working returns picture from facebook as thumbnail-->
								<li class="dropdown">
									<a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Welcome Back, {{ request.user.first_name }} {{ request.user.last_name }} <span class="glyphicon glyphicon-user pull-right"></span></a>
										<ul class="dropdown-menu" role="menu">
											<li><a href="{% url 'upload_images' %}"> My Account <span class="fa fa-cog pull-right"></span></a></li>
											<li class="divider"></li>
											<li><a href="/help/support"> Contact Us <span class="fa fa-envelope pull-right"></span></a></li>
											<li class="divider"></li>
											<li><a href="/accounts/logout"> Logout <span class="fa fa-power-off pull-right"></span></a></li>
										</ul>
								</li>
								<li class="divider-vertical"></li>
							<!-- else user is logged in with registered accounts create the dropdown for them -->
							{% else %}
								<li class="dropdown">
										<a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Welcome Back, {{ request.user.username }} <span class="glyphicon glyphicon-user pull-right"></span></a>
											<ul class="dropdown-menu" role="menu">
												<li><a href="{% url 'upload_images' %}"> My Account <span class="fa fa-cog pull-right"></span></a></li>
												<li class="divider"></li>
												<li><a href="/help/support"> Contact Us <span class="fa fa-envelope pull-right"></span></a></li>
												<li class="divider"></li>
												<li><a href="/accounts/logout"> Logout <span class="fa fa-power-off pull-right"></span></a></li>
											</ul>
									</li>
									<li class="divider-vertical"></li> 
							{% endif %}
                        <!-- else user is not logged in , show him the registration modal -->
						{% else %}
							<li><a href="#myModal" data-toggle="modal" data-target="#myModal">Register</a></li>
							<!-- Modal that includes our registration form -->
								<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
								  <div class="modal-dialog modal-vertical-centered">
									<div class="modal-content">
									  <div class="modal-header">
										<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
										<h4 class="modal-title" id="myModalLabel">Register with Rate My Beard <small>It's free!</small></h4>
									  </div>
									  <div class="modal-body">
											<div class="panel-body">
											<form method="post" action="{% url "account_signup" %}">
											{% csrf_token %}
												<div class="row">
													<div class="col-xs-6 col-sm-6 col-md-6">
														<div class="form-group">
															<input type="text" name="username" id="id_username" class="form-control input-sm" placeholder="User Name">
														</div>
													</div>
												</div>
												<div class="form-group">
													<input type="email" name="email" id="id_email" class="form-control input-sm" placeholder="Email Address">
												</div>
												<div class="row">
													<div class="col-xs-6 col-sm-6 col-md-6">
														<div class="form-group">
															<input type="password" name="password1" id="id_password1" class="form-control input-sm" placeholder="Password">
														</div>
													</div>
													<div class="col-xs-6 col-sm-6 col-md-6">
														<div class="form-group">
															<input type="password" name="password2" id="id_password2" class="form-control input-sm" placeholder="Confirm Password">
														</div>
													</div>
												</div>
												
												<input type="submit" value="Register"  id="signup" class="btn btn-info btn-block">
											</form>
										</div>
									  </div>
									</div><!-- /.modal-content -->
								  </div><!-- /.modal-dialog -->
								</div><!-- /.modal -->
                            <!-- creating our dropdown menu form for login-->
							<li class="divider-vertical"></li> 
							<li class="dropdown">
							<a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Sign In<span class="caret"></span></a>
							<div class="dropdown-menu" role= "menu" style="padding:17px">
								<form method="post" action="{% url "account_login" %}">
								 <h3>Please Log In</h3>
								<form id="login" method="post">
								{% csrf_token %}
								<input style="margin-bottom: 15px;" type="text" placeholder="Username" id="username" name="login" size="30">
								<input style="margin-bottom: 15px;" type="password" placeholder="Password" id="password" name="password" size="30">
								<input style="float: left; margin-right: 10px;" type="checkbox" name="remember-me" id="remember-me" value="1">
									<label class="string optional" for="user_remember_me"> Remember me</label>
									<input class="btn btn-primary btn-block" type="Submit"></input>
									<li class="divider"></li>
									<a class="btn btn-block btn-social btn-facebook" href="/accounts/facebook/login"> <i class="fa fa-facebook"></i> Login with Facebook</a>
									<a class="btn btn-block btn-social btn-google-plus" href="/accounts/google/login"><i class="fa fa-google-plus"></i> Login with google+</a>
								</form>
							</div>
							</li>
						{%endif%}
				</ul>
		</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>
        <div>
		<!-- Button trigger modal -->
		    <!-- main block -->
            {% block body_block %} {% endblock %}
        </div>
        <!-- bootstrap scripts for jquery and our own ajax moved at end for faster loading -->
    	<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.11.2.min.js"></script>
		<script src=" https://cdnjs.cloudflare.com/ajax/libs/jquery-migrate/1.2.1/jquery-migrate.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
		<script src="{% static "js/rmb-ajax.js" %}"></script>

    </body>
</html>

templates/rmb/full.html
<!DOCTYPE html>
{% extends 'rmb/base.html' %}
{% load staticfiles %} <!-- New line -->



{% block body_block %}
<div class="container-fluid main-container">
<div class="row">
	<!-- sidebars for categories and ratings -->
		<div class="col-md-2 sidebar">
			<ul class="nav nav-pills nav-stacked">
				<li class="active"><a href="">Categories</a></li>
				<li><a href="{% url 'full' %}">Full Beards</a></li>
				<li><a href="{% url 'half' %}">Half Beards</a></li>
				<li><a href="{% url 'moustache' %}">Moustaches</a></li>
				<li><a href="{% url 'noob' %}">Noob Beards</a></li>
				<li class="active"><a href="">Ratings</a></li>
				<li><a href="{% url 'index' %}">Top Beards</a></li>
				<li><a href="{% url 'index' %}">New Beards</a></li>
				<li><a id="worst" href="{% url 'worse' %}" data-catid="worst_id">Worst Beards</a></li>
			</ul>
		</div>


        <div class="col-md-10">
        <ul class="nav nav-pills nav-stacked">
				<li class="active"><a href="">Full Beards</a></li>
		</ul>
			<div class="jumbotron" id="likes_main">
                {% for image in all_images %}
                <div class='image_box'>
					<ul class='list-inline'>
                        <li>
                        <div class="well">

                            <a href={{ image.image.url }}>
                            <img src="{{image.image.url}}" alt="{{image.name}}" ></a>

                            <div><strong class="uploadedby">Uploaded By: {{ image.img_user }}</strong></div>
							<div><span class="date">On: {{ image.img_date }}</span></div>

                                {%  for likes in image_likes %}
                                {%  if likes.image_liked == image %}

                                 <button class ="likes btn btn-circle-sm btn-success" data-catid="{{likes.id}}" /><span  class="glyphicon glyphicon-thumbs-up">{{ likes.likes }}</span></button>
							     <button class ="dislikes btn btn-circle-sm btn-danger" data-catid2="{{likes.id}}" /><span class="glyphicon glyphicon-thumbs-down">{{ likes.dislikes }}</span></button>
                                {%  else %}
                                {% endif %}
                                {%  endfor %}
                                <br><br>

                        </div>
                        </li>
                     </ul>
                </div>
            {%  endfor %}
            </div>
        </div>

</div>
</div>
{% endblock %}

templates/rmb/half.html
<!DOCTYPE html>
{% extends 'rmb/base.html' %}
{% load staticfiles %} <!-- New line -->



{% block body_block %}
<div class="container-fluid main-container">
<div class="row">
	<!-- sidebars for categories and ratings -->
		<div class="col-md-2 sidebar">
			<ul class="nav nav-pills nav-stacked">
				<li class="active"><a href="">Categories</a></li>
				<li><a href="{% url 'full' %}">Full Beards</a></li>
				<li><a href="{% url 'half' %}">Half Beards</a></li>
				<li><a href="{% url 'moustache' %}">Moustaches</a></li>
				<li><a href="{% url 'noob' %}">Noob Beards</a></li>
				<li class="active"><a href="">Ratings</a></li>
				<li><a href="{% url 'index' %}">Top Beards</a></li>
				<li><a href="{% url 'index' %}">New Beards</a></li>
				<li><a id="worst" href="{% url 'worse' %}" data-catid="worst_id">Worst Beards</a></li>
			</ul>
		</div>


        <div class="col-md-10">
        <ul class="nav nav-pills nav-stacked">
				<li class="active"><a href="">Half Beards</a></li>
		</ul>
			<div class="jumbotron" id="likes_main">
                {% for image in all_images %}
                <div class='image_box'>
					<ul class='list-inline'>
                        <li>
                        <div class="well">

                            <a href={{ image.image.url }}>
                            <img src="{{image.image.url}}" alt="{{image.name}}" ></a>

                            <div><strong class="uploadedby">Uploaded By: {{ image.img_user }}</strong></div>
							<div><span class="date">On: {{ image.img_date }}</span></div>

                                {%  for likes in image_likes %}
                                {%  if likes.image_liked == image %}

                                 <button class ="likes btn btn-circle-sm btn-success" data-catid="{{likes.id}}" /><span  class="glyphicon glyphicon-thumbs-up">{{ likes.likes }}</span></button>
							     <button class ="dislikes btn btn-circle-sm btn-danger" data-catid2="{{likes.id}}" /><span class="glyphicon glyphicon-thumbs-down">{{ likes.dislikes }}</span></button>
                                {%  else %}
                                {% endif %}
                                {%  endfor %}
                                <br><br>

                        </div>
                        </li>
                     </ul>
                </div>
            {%  endfor %}
            </div>
        </div>

</div>
</div>
{% endblock %}

templates/rmb/moustache.html
<!DOCTYPE html>
{% extends 'rmb/base.html' %}
{% load staticfiles %} <!-- New line -->



{% block body_block %}
<div class="container-fluid main-container">
<div class="row">
	<!-- sidebars for categories and ratings -->
		<div class="col-md-2 sidebar">
			<ul class="nav nav-pills nav-stacked">
				<li class="active"><a href="">Categories</a></li>
				<li><a href="{% url 'full' %}">Full Beards</a></li>
				<li><a href="{% url 'half' %}">Half Beards</a></li>
				<li><a href="{% url 'moustache' %}">Moustaches</a></li>
				<li><a href="{% url 'noob' %}">Noob Beards</a></li>
				<li class="active"><a href="">Ratings</a></li>
				<li><a href="{% url 'index' %}">Top Beards</a></li>
				<li><a href="{% url 'index' %}">New Beards</a></li>
				<li><a id="worst" href="{% url 'worse' %}" data-catid="worst_id">Worst Beards</a></li>
			</ul>
		</div>


        <div class="col-md-10">
        <ul class="nav nav-pills nav-stacked">
				<li class="active"><a href="">Moustaches</a></li>
		</ul>
			<div class="jumbotron" id="likes_main">
                {% for image in all_images %}
                <div class='image_box'>
					<ul class='list-inline'>
                        <li>
                        <div class="well">

                            <a href={{ image.image.url }}>
                            <img src="{{image.image.url}}" alt="{{image.name}}" ></a>

                            <div><strong class="uploadedby">Uploaded By: {{ image.img_user }}</strong></div>
							<div><span class="date">On: {{ image.img_date }}</span></div>

                                {%  for likes in image_likes %}
                                {%  if likes.image_liked == image %}

                                 <button class ="likes btn btn-circle-sm btn-success" data-catid="{{likes.id}}" /><span  class="glyphicon glyphicon-thumbs-up">{{ likes.likes }}</span></button>
							     <button class ="dislikes btn btn-circle-sm btn-danger" data-catid2="{{likes.id}}" /><span class="glyphicon glyphicon-thumbs-down">{{ likes.dislikes }}</span></button>
                                {%  else %}
                                {% endif %}
                                {%  endfor %}
                                <br><br>

                        </div>
                        </li>
                     </ul>
                </div>
            {%  endfor %}
            </div>
        </div>

</div>
</div>
{% endblock %}

templates/rmb/profile.html
<!DOCTYPE html>

{% extends 'rmb/base.html' %}
{% load staticfiles %} <!-- New line -->


{% block body_block %}


<div class="container-fluid main-container">
    <div class="row">
		<div class="col-md-2 sidebar">
			<ul class="nav nav-pills nav-stacked">
				<li class="active"><a href="{% url 'index' %} ">Home</a></li>
				<li><a href="{% url 'index' %} ">Top Beards</a></li>
				<li><a href="{% url 'newest' %} ">New Beards</a></li>
				<li><a id="worst" href="#" data-catid="worst_id">Worst Beards</a></li>
			</ul>
		</div>
            <div class="col-md-10">
                 <div class="jumbotron" id="likes_main">

                     <div class='image_box'>
                          <form class="upload_form" role="form" method="post"action="/rmb/profile/" enctype="multipart/form-data">
                              {% csrf_token %}
                                <h2 class="form-upload-heading">Upload Image</h2>

                                 {% csrf_token %}
                              {{ upload_image.image }}<br>
                                <input class="form-control" placeholder="image name" id="id_image" maxlength="30" name="img_name" type="text" required autofocus=""/>
                         <br>   {{ upload_image.img_cat_id }}<br><br>
                            <button class="btn btn-lg btn-primary btn-block" type="submit" value="Submit" />Upload</button>
                         </form>
                        <br> <br>
                        <P>Images Uploaded</P>
                          {% for image in all_images %}
                            <div class = img-thumbnail>
                                <a href={{ image.image.url }}>
                                <img src="{{image.image.url}}" alt="{{image.name}}" >
                                </a>
                            </div>
                            {%  endfor %}
                     </div>
            </div>
        </div>
</div>
{% endblock %}